### ISSUE TITLE
Missing highlighting for html tags

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-docs#2273]
Example https://code.visualstudio.com/docs/nodejs/vuejs-tutorial#_hello-world

Using similar CSS selector to fix:
```css
.hljs-tag > .hljs-title {
    color: #0072be;
}
```
