### ISSUE TITLE
Should `code` tags have nowrap?

### ISSUE THREAD

**Issue by usernamehw** [microsoft/vscode-docs#2275]
It's impossible to find all the places where `&nbsp;` is needed. But there's a way to do literally 0 work.

```css
code {
    white-space: nowrap;
}
```

Before:
![before](https://user-images.githubusercontent.com/9638156/49906029-33514300-fe81-11e8-8b1f-f15ce7f6b7ff.png)

After:
![after](https://user-images.githubusercontent.com/9638156/49906034-39dfba80-fe81-11e8-9290-10c25a195691.png)

Before:
![before](https://user-images.githubusercontent.com/9638156/50018564-cc4aa000-ffe0-11e8-8254-c9a1cd3cc72c.png)

After:
![after](https://user-images.githubusercontent.com/9638156/50018572-d53b7180-ffe0-11e8-8371-1514584229e2.png)

**Comment by usernamehw** [comment]
There could be a scroll on mobile (didn't test) ... but still pretty doable:
```css
@media only screen and (min-width: 800px)  {
    code {
        white-space: nowrap;
    }
}
```
